# Site wide configuration

title:            me.__init__
locale:           en_US
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown # redcarpet # kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pankaj Prateek
  avatar: me.jpg
  bio: "A lazy Computer G33k, Programmer, Linux Enthusiast, Blogger, Tech Savvy, Foodophile"
  email: pankaj200292@gmail.com
  disqus-shortname: 
  twitter: pankaj_prateek
  facebook: pankaj.prateek
  google:
    plus: pankaj200292
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: pankajprateek
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: pankajprateek
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "CNAME", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
